# Generated by Django 4.2.7 on 2024-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrupt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrupt',
            name='bankrupt_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
